### ISSUE TITLE
1.3 multiplayer bugs

### ISSUE THREAD

**Issue by PyroThunderzz** [thetrueoneshots/PyroProgression#6]
Current stats of the player that joins is not set when you immediately recenter. ( Max hp, stats/gear level )

Health bar glitch on entities appears off your screen when joining someone's game

![Screenshot (7)](https://user-images.githubusercontent.com/102264746/159809771-bde1a4ab-2254-4754-91f6-f84f7d166a34.png)

**Comment by thetrueoneshots** [comment]
Thanks for letting me know. I think this issue has to do with the recalculation of health that is set only once. The amount of extra health should go away after the first hit of an enemy or whenever the creature attacks something. For now this is not a gamebreaking bug, but I agree it should be fixed. I will look into it.

Can you describe all the gear and player issues in more detail? As I am not sure what that issue is exactly!

**Comment by thetrueoneshots** [comment]
Should have fixed this with the newest update. Let me know if it is fixed with the newest update (1.4) that I will release in a second. Thanks.
