### ISSUE TITLE
General bugs/ideas

### ISSUE THREAD

**Issue by PyroThunderzz** [thetrueoneshots/PyroProgression#7]
-You can't identify what class a piece of gear is until you hit that level (gives false hope/excitement)
-Level cap should be increased to 5 for more variety in difficulty as well as increasing stats in between each level (both player and enemies). maybe increase the gear restriction to 1 instead of zero? (gives more movement for equipping gear)
-Xp needs to be reworked similar to 1.1 of PyroProgression. (visually unpleasant and weird to look at)

**Comment by thetrueoneshots** [comment]
- Yes that is indeed true. I think that it does maybe indeed give false hope, but is not game breaking and kind of hard to fix because it will require extra hooks. It is a quality of life issue.
- Is the level cap in a region not already at 5?
- Yes I do agree that the previous XP system might be better. I will work on it.

**Comment by thetrueoneshots** [comment]
Okay so for next time please make it all seperate issues so I can resolve and close any of them seperately. I have modified the XP system and also the effect of levels and stats.
